### ISSUE TITLE
tt-metal-ci-vm-t3k-02 nonfunctional

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#12915]

**Comment by blozano-tt** [comment]
Hangs eternally at ensure weka mount active. Reprovision??

https://github.com/tenstorrent/tt-metal/actions/runs/12312002998/job/34363442017

```
Prepare all required actions
Run ./.github/actions/ensure-active-weka-mount
  with:
  env:
    TT_METAL_ENV: 
    ARCH_NAME: wormhole_b0
    LOGURU_LEVEL: INFO
    LD_LIBRARY_PATH: /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib
    TT_METAL_HOME: /home/ubuntu/actions-runner/_work/tt-metal/tt-metal
Run sudo systemctl restart mnt-MLPerf.mount
  sudo systemctl restart mnt-MLPerf.mount
  sudo /etc/rc.local
  ls -al /mnt/MLPerf/bit_error_tests
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TT_METAL_ENV: 
    ARCH_NAME: wormhole_b0
    LOGURU_LEVEL: INFO
    LD_LIBRARY_PATH: /home/ubuntu/actions-runner/_work/tt-metal/tt-metal/build/lib
    TT_METAL_HOME: /home/ubuntu/actions-runner/_work/tt-metal/tt-metal
```
