### ISSUE TITLE
Check that all dockerized flows are uploading uuid test artifacts from the right location

### ISSUE THREAD

**Issue by williamlyTT** [tenstorrent/tt-metal#19097]
I.e. for jobs running in containers
```
- uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
          prefix: "test_reports_"
```

to

```
- uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          path: |
            /work/generated/test_reports/
          prefix: "test_reports_"
```

**Comment by williamlyTT** [comment]
See oopsie: https://github.com/tenstorrent/tt-metal/pull/19098

**Comment by williamlyTT** [comment]
Also check GTEST_OUTPUT env var

**Comment by blozano-tt** [comment]
Can we just update the default here?

```
name: "Upload artifact with a uuid"
description: "Upload artifact with a uuid for later identification with the job"

inputs:
  path:
    description: "Paths to pass to upload-artifact and upload"
    required: true
```
