### ISSUE TITLE
Set a default path for superset uuid artifact upload

### ISSUE THREAD

**Issue by williamlyTT** [tenstorrent/tt-metal#19375]
Annoying to have to know between 

docker-run: generated/test_reports/
containerized: /work/generated/test_reports/

Hide this logic inside the github action and get rid of the paths everywhere unless specifically different (only ones I know in off the top of my head are tt-train ctest_output.txt and smoke test xml)

Clunky in general
```
- uses: tenstorrent/tt-metal/.github/actions/upload-artifact-with-job-uuid@main
        timeout-minutes: 10
        if: ${{ !cancelled() }}
        with:
          path: |
            generated/test_reports/
```
