### ISSUE TITLE
Add Superset uploading for TG demos pipeline (only Falcon7b for now)

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#20168]
We are currently missing the "Save environment data" and "Upload benchmark data" steps for the [TG demos pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/tg-demo-tests.yaml). E.g. already exists for the [T3K demos pipeline](https://github.com/tenstorrent/tt-metal/actions/workflows/t3000-demo-tests.yaml).

Change should be something along the lines of the code below, with tweaks to allow `benchmark_data_batchfile.txt` to find the benchmark data jsons under /work/generated instead of ./generated since this pipeline uses /work for tt-metal.
```
      - name: Save environment data
         if: ${{ (matrix.test-group.name == 'TG Falcon7b demo tests') && !cancelled() }}
         run: |
           python3 .github/scripts/data_analysis/create_benchmark_with_environment_json.py
       - name: Upload benchmark data
         if: ${{ (matrix.test-group.name == 'TG Falcon7b demo tests') && !cancelled() }}
         uses: ./.github/actions/upload-data-via-sftp
         with:
           ssh-private-key: ${{ secrets.SFTP_BENCHMARK_WRITER_KEY }}
           sftp-batchfile: .github/actions/upload-data-via-sftp/benchmark_data_batchfile.txt
           username: ${{ secrets.SFTP_BENCHMARK_WRITER_USERNAME }}
           hostname: ${{ secrets.SFTP_BENCHMARK_WRITER_HOSTNAME }}
```
