### ISSUE TITLE
Re-use built artifacts in `build-artifact.yaml` workflow in `docs-latest-public.yaml`

### ISSUE THREAD

**Issue by dimitri-tenstorrent** [tenstorrent/tt-metal#8097]
The `docs-latest-public.yaml` is rebuilding the libraries from scratch in the steps:
```
      - uses: ./.github/actions/install-metal-deps
        with:
          os: ubuntu-20.04
      - uses: ./.github/actions/install-metal-dev-deps
        with:
          os: ubuntu-20.04
      - name: Build tt-metal
        run: |
          export TT_METAL_HOME=$(pwd)
          make build
```

This is a duplicated effort and increases the delay before the docs are published. Re-use the existing artifacts created at an earlier step such as the one in `build-artifact.yaml`
